### ISSUE TITLE
No triggering on MasterFire

### ISSUE THREAD

**Issue by Jhsmit** [PRNicovich/NicoLase#1]
Hi, thanks for uploading this, its seems to do exactly what I was looking for. However, I have some troubles with the camera triggering. The pushbutton works for me, but I cant get the camera to trigger the sequence. If I look at the arduino code, I can't see how to inititate the main loop (pre - acquisition - post) or how the digital interrupt from pin 2 trigger the sequence. Am I missing something or do I need more code than just SerialSequenceUploader.ino to make it work?

**Comment by PRNicovich** [comment]
Very glad to hear this project is helpful!  And my apologies that it is giving you trouble. 

You are correct that the code had that error.  I must have had the old (incorrect) version of that code in this repo and was working from a newer, private one.  

The issue in the Arduino sketch has been corrected.  This sketch is the one we are using in active instruments.  You can pull the update and hopefully that will solve the problem on your end.

**Comment by Jhsmit** [comment]
Thanks for the update, it appears to be working now. Just have to do some tinkering and checking to make sure the timing is perfect. I'm writing a python GUI, I hope to make that public soon, in case you're interested.
